# -*- coding: utf-8 -*-
"""
/***************************************************************************
 WeedsDeep
                                 A QGIS plugin
 WeedsDeep project.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-03-21
        copyright            : (C) 2019 by Lorenzo Giuliani
        email                : lorenzogiuliani95@hotmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load WeedsDeep class from file WeedsDeep.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .weedsdeep_processing import WeedsDeep
    return WeedsDeep(iface)
